server:
  port: 80
#  127.0.0.1 file.service.com www.gmall.com item.gmall.com order.gmall.com payment.gmall.com
#  127.0.0.1 seckill.gmall.com passport.gmall.com cart.gmall.com search.gmall.com api.gmall.com
ipAddr: 192.168.134.11
spring:
  redis:
    host: ${ipAddr} #老师的阿里云redis
    port: 6389
  application:
    name: shop-gateway
  cloud:
    nacos:
      discovery:
        server-addr: ${ipAddr}:8848
    gateway:
      discovery:      #是否与服务发现组件进行结合，通过 serviceId(必须设置成大写) 转发到具体的服务实例。默认为false，设为true便开启通过服务中心的自动根据 serviceId 创建路由的功能。
        locator:      #路由访问方式：http://Gateway_HOST:Gateway_PORT/大写的serviceId/**，其中微服务应用名默认大写访问。
          enabled: true
      routes:
        - id: shop-product
          uri: lb://shop-product
          predicates:
            - Path=/product/**
#            - Path=/** # 路径匹配
#        - id: shop-web
#          uri: lb://shop-web
#          predicates:
#            - Host=item.gmall.com,www.gmall.com,search.gmall.com
        - id: shop-product
          uri: lb://shop-product
          predicates:
            - Path=/sku/**
        - id: shop-user
          uri: lb://shop-user
          predicates:
            - Path=/user/**
        - id: shop-cart
          uri: lb://shop-cart
          predicates:
            - Path=/cart/**
        - id: shop-order
          uri: lb://shop-order
          predicates:
            - Path=/order/**
        - id: shop-payment
          uri: lb://shop-payment
          predicates:
            - Path=/payment/**
        - id: shop-seckill
          uri: lb://shop-seckill
          predicates:
            - Path=/seckill/**
        #主机地址匹配
        - id: shop-web
          uri: lb://shop-web
          predicates:
            - Host=item.gmall.com,seckill.gmall.com,payment.gmall.com,order.gmall.com,cart.gmall.com,passport.gmall.com,search.gmall.com,www.shop.com
#        - id: shop-www
#          uri: lb://shop-web
#          predicates:
#            - Host=www.shop.com
#        - id: shop-www
#          uri: lb://shop-web
#          predicates:
#            - Host=search.gmall.com
#        - id: web-passport
#          uri: lb://shop-web
#          predicates:
#            - Host=passport.gmall.com
#        - id: web-cart
#          uri: lb://shop-web
#          predicates:
#            - Host=cart.gmall.com
#        - id: web-order
#          uri: lb://shop-web
#          predicates:
#            - Host=order.gmall.com
#        - id: web-payment
#          uri: lb://shop-web
#          predicates:
#            - Host=payment.gmall.com
#        - id: web-seckill
#          uri: lb://shop-web
#          predicates:
#            - Host=seckill.gmall.com

filter:
  whiteList: "order.html"


